### ISSUE TITLE
Wrong person for Prince Philippe in Belgium 

### ISSUE THREAD

**Issue by ogregoire** [mihaiolteanu/ulitza#2]
In Belgium, I can see the following:

> Prince Philip, Duke of Edinburgh (4) 

No. The four streets are named following our current [king Philippe](https://en.wikipedia.org/wiki/Philippe_of_Belgium), previously prince, and not the late Duke of Edinburgh.

Monarchy is the only exception to the rule in Belgium that streets must bear the name of dead people.

**Comment by mihaiolteanu** [comment]
Hello Olivier,

Thank you for your input.
I will modify it. If you have the time, you can consider opening a PR from your side and I will merge it.

Mihai

**Comment by mihaiolteanu** [comment]
> Monarchy is the only exception to the rule in Belgium that streets must bear the name of dead people.

Yes, I've seen this in a number of countries. That is, some streets are named after living persons and not of deceased ones only. I haven't seen that where I am living (Romania), so I was quite confused at first. Thank you for the confirmation and clarification.
